name: MasterFastfile CI

on:
  pull_request:
    branches: [ '*' ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: Install dependencies
      run: bundle install
    - name: Run rubocop
      run: bundle exec rubocop
